---
title: "project 2"
output: html_notebook
---

```{r warning=FALSE}
library(readr)
library(tidyr)
library(plyr)
library(shiny)
library(magrittr)
library(echarts4r)
library(shinythemes)
library(shinyWidgets)
library(golem)
library(typed)
```

```{r}
arrest_2021 <- read.csv("../data/NYPD_Arrest_Data__Year_to_Date_.csv")
arrest_his <- read_csv("../data/NYPD_Arrests_Data__Historic_.csv")
# names(arrest_2021)
# names(arrest_his)
```

```{r}
# Check if there is any missing or malformed date
# nhis <- dim(arrest_his)[1]
# n21 <- dim(arrest_2021)[1]
# sum(is.na(arrest_his$ARREST_DATE)) == 0
# sum(is.na(arrest_2021$ARREST_DATE)) == 0
# pat <- "[0-9][0-9]?/[0-9][0-9]?/[0-9]{4}"
# length(grep(pat, arrest_his$ARREST_DATE)) == nhis
# length(grep(pat, arrest_2021$ARREST_DATE)) == n21


# Transform format, extract year, give up useless data and variables
arrest_his$ARREST_DATE <- as.Date(arrest_his$ARREST_DATE, "%m/%d/%Y")
arrest_2021$ARREST_DATE <- as.Date(arrest_2021$ARREST_DATE, "%m/%d/%Y")
arrest_his$Year <- as.integer(format(arrest_his$ARREST_DATE, format = "%y"))
# table(arrest_his$Year)
arrest_2021$Year <- 21
# arrest_2021$Year <- as.integer(format(arrest_2021$ARREST_DATE, format = "%y"))
# table(arrest_2021$Year)
arrest_his <- arrest_his[arrest_his$Year > 17, c(2, 6, 9, 10, 12, 13, 14, 20)]
arrest_2021 <- arrest_2021[, c(2, 6, 9, 10, 12, 13, 14, 20)]
```

```{r}

# Combine two data sets and further clean the data
arrest <- rbind(arrest_his, arrest_2021)
names(arrest)
# sum(is.na(arrest$OFNS_DESC))
# sum(is.na(arrest$ARREST_BORO))
# sum(is.na(arrest$ARREST_PRECINCT))
# sum(is.na(arrest$AGE_GROUP))
# sum(is.na(arrest$PERP_SEX))
# sum(is.na(arrest$PERP_RACE))
arrest <- arrest[!is.na(arrest$OFNS_DESC), ]
# table(arrest$OFNS_DESC)
# table(arrest$ARREST_BORO)
# table(arrest$ARREST_PRECINCT)
# table(arrest$AGE_GROUP)
# table(arrest$PERP_SEX)
# table(arrest$PERP_RACE)
arrest <- arrest[arrest$PERP_RACE != "UNKNOWN", ]
arrest <- arrest[arrest$OFNS_DESC != "", ]
ofns <- names(table(arrest$OFNS_DESC))

```

```{r}
ofns
```


```{r}
a <- ofns[c(2, 10, 11, 14, 20, 24, 29, 32, 34, 38, 38, 40, 44, 44, 48, 48, 48, 48, 52, 54, 57, 59, 59, 65, 66, 66, 72, 83, 83, 17)]
b <- ofns[c(3, 9, 12, 13, 19, 25, 30, 33, 35, 36, 37, 39, 42, 43, 45, 46, 47, 31, 51, 55, 56, 58, 60, 64, 67, 68, 73, 81, 80, 82)]
arrest$OFNS_DESC <- mapvalues(arrest$OFNS_DESC, b, a)
t <- table(arrest$OFNS_DESC)

```

```{r}
ofns <- names(t)
a <- c(rep("ADMINISTRATIVE $ HEALTH CODES", 2), rep("OTHER LAWS", 4), rep("ASSAULT", 2), rep("VEHICLE AND TRAFFIC", 3), rep("OFFENSES", 10), rep("THEFT & LARCENY", 5))
b <- ofns[c(2, 34, 3, 4, 35, 42, 7, 19, 27, 43, 53, 5, 29, 36, 37, 38, 39, 40, 41, 44, 47, 24, 45, 46, 51, 52)]
arrest$OFNS_DESC <- mapvalues(arrest$OFNS_DESC, b, a)
t <- sort(table(arrest$OFNS_DESC), decreasing = TRUE)
ofns <- names(t)
a <- c("THEFT & LARCENY", rep("OTHER", 23))
b <- ofns[10:33]
arrest$OFNS_DESC <- mapvalues(arrest$OFNS_DESC, b, a)


# create the "Year_Quarter" and "Race_Sex" variables
Month <- as.integer(format(arrest$ARREST_DATE, format = "%m"))
n <- dim(arrest)[1]
Month <- Month-1
arrest$Quarter <- Month%/%3 + 1
arrest <- unite(arrest, "Year_Quarter", Year, Quarter)
arrest <- unite(arrest, "Race_Sex", PERP_RACE, PERP_SEX)
```

```{r}
app_server <- function(input, output, session) {

  echarts4r::e_common(
    font_family = "Playfair Display",
    theme = "vintage"
  )

  output$title <- typed::renderTyped({
    typed::typed(c("Freedom of Fake news^1000", "Freedom of Press Index^500<br>A Visualisation"), typeSpeed = 25, smartBackspace = TRUE)
  })

#  callModule(mod_ts_server, "ts")
  callModule(mod_map_server, "map")

}
```

```{r}
app_ui <- function() {

  options <- list()

  tagList(
    # Leave this function for adding external resources
    golem_add_external_resources(),
    # List the first level UI elements here 
    pagePiling(
      sections.color = c('#2f2f2f'
                         , '#2f2f2f'
                         #, '#f9f7f1', '#2f2f2f'
                         ),
      opts = options,
      menu = c(
#        "Home" = "home",
        "Map" = "map"
        #,
        #"Series" = "ts",
        #"About" = "about"
      ),
 #     pageSectionImage(
  #      center = TRUE,
#        img = "www/img/reading.jpg",
   #     menu = "home",
  #      h1(typed::typedOutput("title"), class = "header shadow-dark"),
  #      h3(
  #        class = "light footer",
  #        "by", tags$a("news-r", href = "https://news-r.org", class = "link"), "with", emo::ji("coffee")
  #      )
  #    ),
#      pageSection(
 #       center = TRUE,
  #      menu = "map",
   #     mod_map_ui("map")
    #  ),
      pageSection(
        center = TRUE,
        menu = "ts",
        mod_ts_ui("ts")
      )
  #    pageSection(
   #     center = TRUE,
    #    menu = "about",
     #   h1("About", class = "header shadow-dark"),
      #  h2(
       #   class = "shadow-light",
        #  tags$a("The code", href = "https://github.com/news-r/fopi.app", target = "_blank", class = "link"),
#          "|",
 #         tags$a("The API", href = "https://github.com/news-r/fopi", target = "_blank", class = "link")
  #      ),
   #     h3(
    #      class = "light footer",
     #     "by", tags$a("news-r", href = "https://news-r.org", class = "link"), "with", emo::ji("coffee")
      #  )
      #)
    )
  )
}

#' @import shiny
#golem_add_external_resources <- function(){
  
 # addResourcePath(
 #   'www', system.file('app/www', package = 'fopi.app')
#  )
 
#  tags$head(
#    golem::activate_js(),
#    golem::favicon(),
#    tags$link(
#      rel = "stylesheet", href = shinythemes::shinytheme("sandstone")
#    ),
 #   tags$link(rel = "stylesheet", type = "text/css", href = "www/css/style.css"),
 #   tags$script(async = NA, src = "https://www.googletagmanager.com/gtag/js?id=UA-74544116-1"),
 #   tags$script(
  #    "window.dataLayer = window.dataLayer || [];
#  function gtag(){dataLayer.push(arguments);}
#  gtag('js', new Date());
 # gtag('config', 'UA-74544116-1');"
#    )
#  )
#}
```

```{r}
cns <- arrest %>% 
      dplyr::arrange(OFNS_DESC) %>% 
      dplyr::distinct(OFNS_DESC) %>% 
      dplyr::pull(OFNS_DESC)
```

```{r}
library(ggplot2)
```


```{r}

  temp <- arrest %>% 
      dplyr::mutate(Year_Quarter = as.character(Year_Quarter)) %>% 
      dplyr::arrange(Year_Quarter) %>% 
      dplyr::filter(OFNS_DESC %in% cns) %>% 
      dplyr::group_by(Year_Quarter)%>%
      dplyr::summarise(total_count  = n())

```


```{r}
  selecteddata <- arrest %>% 
      dplyr::mutate(Year_Quarter = as.character(Year_Quarter)) %>% 
      dplyr::arrange(Year_Quarter) %>% 
      dplyr::filter(OFNS_DESC %in% cns) %>% 
      dplyr::group_by(OFNS_DESC,Year_Quarter)%>%
      dplyr::summarise(count = n())%>%
      left_join(temp, by = "Year_Quarter")%>%
      dplyr::mutate(percentage = count/total_count)


```

```{r}
plot(selecteddata$Year_Quarter,selecteddata$n)
```


```{r}
shinyApp(ui = fluidPage(
  titlePanel("My Shiny App"),
  sidebarLayout(
    sidebarPanel(
          selectInput('criminal_type', 'Select criminal type',
              choices = cns,
              multiple = TRUE,
              selected = sample(cns, 2))),
    
    # Show a plot of the generated distribution
    mainPanel(
       plotOutput("trend")
    ))),
#      tabsetPanel(
 #     tabPanel('server.R',
  #             code('library(shiny)

server = function(input, output) {
    selected_data <- reactive({arrest %>% 
      dplyr::mutate(Year_Quarter = as.character(Year_Quarter)) %>% 
      dplyr::arrange(Year_Quarter) %>% 
      dplyr::filter(OFNS_DESC %in% input$criminal_type) %>% 
      dplyr::group_by(OFNS_DESC,Year_Quarter)%>%
      dplyr::count()})
    
     output$trend <- renderPlot({
      ggplot(data = selected_data(), aes(x = Year_Quarter, y = n, color = OFNS_DESC, group = OFNS_DESC))+
    geom_point()+
      geom_line()
    
  })

},
options = list(height = 600))

#')
 #              ),
  #    tabPanel('ui.R',
 #              code('shinyUI(

#fluidPage(
 #wellPanel(
 #       selectInput("select", label = h3("Select box"), 
  #      p("Current Value:", style = "color:#888888;"),
   #     choices = list("Choice 1" = cns[1], "Choice 2" = cns[2],
    #                   "Choice 3" = cns[3], "Choice 4" = cns[4],
     #                  "Choice 5" = cns[5], "Choice 6" = cns[6],
      #                 "Choice 7" = cns[7], "Choice 8" = cns[8],
       #                "Choice 9" = cns[9], "Choice 10" = cns[10]), selected = 1),
#        hr(),
 #      
  #      verbatimTextOutput("select")
   3     
#      )
#  )
#)')
#               )
#    )
#  )
#)
#    )
#  )

```

```{r}
fluidPage(
    titlePanel("Count of criminal types through time"),
    fluidRow(
      column(
        6,
        uiOutput("criminal_type")
      ),
      column(
        6,
        shinyWidgets::radioGroupButtons(
          inputId = "value",
          label = "Metric",
          choices = c("count", "percent"),
          checkIcon = list(
            yes = icon("ok",
            lib = "glyphicon")
          )
        )
      )
    ),
    plotOutput("trend", height="50vh")
)
```


```{r}    
# Module Server
    
#' @rdname mod_ts
#' @export
#' @keywords internal
    
    function(input, output){
  
  
  output$criminal_type <- renderUI({
    cns <- arrest %>% 
      dplyr::arrange(OFNS_DESC) %>% 
      dplyr::distinct(OFNS_DESC) %>% 
      dplyr::pull(OFNS_DESC)

    selectizeInput(
      "criminal_type",
      "Search a criminal type",
      choices = cns,
      selected = sample(cns, 2),
      multiple = TRUE
    )
  })
  
  output$trend <- echarts4r::renderEcharts4r({
    req(input$criminal_type)

    msg <- paste0(tools::toTitleCase(input$value), ", the lower the better")

    arrest %>% 
      dplyr::mutate(Year_Quarter = as.character(Year_Quarter)) %>% 
      dplyr::arrange(Year_Quarter) %>% 
      dplyr::filter(OFNS_DESC %in% input$criminal_type) %>% 
      dplyr::group_by(OFNS_DESC) %>% 
      echarts4r::e_charts(Year_Quarter) %>% 
      echarts4r::e_line_(input$value) %>% 
      echarts4r::e_tooltip(trigger = "axis") %>% 
      echarts4r::e_y_axis(inverse = TRUE) %>% 
      echarts4r::e_axis_labels("Year_Quarter") %>% 
      echarts4r::e_title(msg) %>% 
      echarts4r::e_color(
        c("#247BA0", "#FF1654", "#70C1B3", "#2f2f2f", "#F3FFBD", "#B2DBBF")
      )
  })
    }
```

```{r}
ui <- fluidPage(
  counterButton("counter1")
)

server <- function(input, output, session) {
  counterServer("counter1")
}
```


```{r}
shinyApp(ui, server)
```




